// Auto-generated from Xslide Maintenance Master V2.xlsx

export const SEED_TICKETS = [
  {
    scooterId: "23300",
    city: "Corinth",
    dateEntered: "2026-02-05",
    issueDescription: "Loose Neck, BLs are done",
    category: "B",
    status: "Blocked",
    primaryTag: "Loose Neck, Brake Lines",
    secondaryTag: "Routine Maintenance, Parts Required",
    dateCompleted: null,
    notes: "Brake lines are fucked, both, check if re-tightening worked, otherwise, swap out bearings"
  },
  {
    scooterId: "25860",
    city: "Nafplion",
    dateEntered: "2026-01-05",
    issueDescription: "Stiff Neck,need new brake line",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-07-04",
    notes: "Fixed by Heimir"
  },
  {
    scooterId: "24606",
    city: "Nafplion",
    dateEntered: "2026-03-02",
    issueDescription: "09E, throttle issue",
    category: "Q",
    status: "Backlog",
    primaryTag: "Throttle, Inspection",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "Came from nafplion today, with throttle issues"
  },
  {
    scooterId: "69298",
    city: "Corinth",
    dateEntered: "2025-11-12",
    issueDescription: "Motor Replacement, Loose Neck, Needs IoT, New Brake Lines",
    category: "B",
    status: "Blocked",
    primaryTag: "Motor/Tire, Brake Lines, IoT",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "71179",
    city: "Corinth",
    dateEntered: "2025-08-01",
    issueDescription: "Lockbox issue, no ecu, no iot",
    category: "C",
    status: "Investigation",
    primaryTag: "Inspection",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Brake lever is fixed, new IoT doesn't work, new battery doesn't work, new ECU doesn't work, new power cable doesn't work, Abnormal Voltage"
  },
  {
    scooterId: "76300",
    city: "Corinth",
    dateEntered: "2025-09-19",
    issueDescription: "Handlebar centering Bolt is broken, missing both brake levers and brake lines, needs new motor,IoT",
    category: "B",
    status: "Blocked",
    primaryTag: "Tooling Required, Unknown Process, Brake Lines, Motor/Tire, IoT",
    secondaryTag: "Parts Required, Bolt Extractor Kit Required",
    dateCompleted: null,
    notes: "Might need a new bolt extraction kit"
  },
  {
    scooterId: "54064",
    city: "Corinth",
    dateEntered: "2025-09-07",
    issueDescription: "Under water, needs inspection, Loose Neck, need IoT",
    category: "B",
    status: "Blocked",
    primaryTag: "Inspection, IoT, Loose Neck",
    secondaryTag: "Parts Required",
    dateCompleted: null,
    notes: "Will need complete inspection"
  },
  {
    scooterId: "31886",
    city: "Corinth",
    dateEntered: "2025-12-02",
    issueDescription: "Brake Line FR, Loose Neck, IoT, Bearing Change",
    category: "B",
    status: "Blocked",
    primaryTag: "Brake Lines, Loose Neck, IoT, Tooling Required",
    secondaryTag: "Parts Required",
    dateCompleted: null,
    notes: "Need to replace Brake Lines F&R, replace bearing, install IoT"
  },
  {
    scooterId: "41430",
    city: "Corinth",
    dateEntered: "2025-03-23",
    issueDescription: "Neck needs bearings, IoT, hidden issues maybe",
    category: "B",
    status: "Blocked",
    primaryTag: "IoT, Inspection",
    secondaryTag: "Parts Required",
    dateCompleted: null,
    notes: "Approach only if neck process plus 90 mins buffer"
  },
  {
    scooterId: "57190",
    city: "Corinth",
    dateEntered: "2026-02-22",
    issueDescription: "Motor Replacement",
    category: "B",
    status: "Blocked",
    primaryTag: "Tooling Required, Motor/Tire, Unknown Process, IoT",
    secondaryTag: "Parts Required, Bolt Extractor Kit Required",
    dateCompleted: null,
    notes: "Brake hub screw is completely destroyed"
  },
  {
    scooterId: "70101",
    city: "Corinth",
    dateEntered: "2026-02-22",
    issueDescription: "Motor Replacement",
    category: "B",
    status: "Blocked",
    primaryTag: "Tooling Required, Motor/Tire, Unknown Process, IoT",
    secondaryTag: "Parts Required, Bolt Extractor Kit Required",
    dateCompleted: null,
    notes: "Brake hub screw is completely destroyed"
  },
  {
    scooterId: "59431",
    city: "Corinth",
    dateEntered: "2025-09-24",
    issueDescription: "Front Fork, front wheel inspection, IoT, kickstand, bolts warped,",
    category: "B",
    status: "Blocked",
    primaryTag: "Tooling Required, Unknown Process, IoT, Front Fork",
    secondaryTag: "Parts Required, Bolt Extractor Kit Required",
    dateCompleted: null,
    notes: "Need to confirm spare parts exist plus if bolt extraction process works"
  },
  {
    scooterId: "19340",
    city: "Corinth",
    dateEntered: "2026-01-28",
    issueDescription: "Unresponsive, screen doesn't open when charging, probably meter",
    category: "B",
    status: "Blocked",
    primaryTag: "Inspection, Unknown Process",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Father swapped out meter but didn't connect new meter in, needs heavy inspection with Diagnostic tool"
  },
  {
    scooterId: "70507",
    city: "Nafplion",
    dateEntered: "2025-12-26",
    issueDescription: "Neck Broken, No IoT, take neck from 45704",
    category: "B",
    status: "Blocked",
    primaryTag: "IoT, Unknown Process",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "We need to transfer neck to this scooter, hardware only, electronics are probably fried"
  },
  {
    scooterId: "80782",
    city: "Nafplion",
    dateEntered: "2025-09-16",
    issueDescription: "Throttle Missing, Twisted Neck",
    category: "B",
    status: "Blocked",
    primaryTag: "Throttle, Twisted Neck",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Need to take from Donor 35960"
  },
  {
    scooterId: "56838",
    city: "Nafplion",
    dateEntered: "2025-10-06",
    issueDescription: "Loose Neck, Bolt is destroyed",
    category: "B",
    status: "Blocked",
    primaryTag: "Loose Neck, Tooling Required, Unknown Process, Inspection",
    secondaryTag: "Bolt Extractor Kit Required",
    dateCompleted: null,
    notes: "Bolt in metal sleeve spins in place, after that, PT wasn't able to fix loose neck while following SOP, needs inspection"
  },
  {
    scooterId: "69996",
    city: "Corinth",
    dateEntered: "2025-03-11",
    issueDescription: "Donor",
    category: "Donor",
    status: "Donor",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "41384",
    city: "Corinth",
    dateEntered: "2025-03-10",
    issueDescription: "Donor",
    category: "Donor",
    status: "Donor",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "81043",
    city: "Corinth",
    dateEntered: "2025-05-11",
    issueDescription: "Donor",
    category: "Donor",
    status: "Donor",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "84850",
    city: "Corinth",
    dateEntered: "2025-06-20",
    issueDescription: "Donor",
    category: "Donor",
    status: "Donor",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "35966",
    city: "Nafplion",
    dateEntered: "2025-09-12",
    issueDescription: "Headlight off, missing pedal pad",
    category: "Donor",
    status: "Donor",
    primaryTag: "Unknown Process, Inspection",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Donor for 2022 Model"
  },
  {
    scooterId: "18741",
    city: "Nafplion",
    dateEntered: "2025-08-09",
    issueDescription: "Donor",
    category: "Donor",
    status: "Donor",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: null,
    notes: ""
  },
  {
    scooterId: "39583",
    city: "Corinth",
    dateEntered: "2026-02-09",
    issueDescription: "Loose Neck",
    category: "C",
    status: "Investigation",
    primaryTag: "Loose Neck, Unknown Process",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "Need to understand how bearing tool works"
  },
  {
    scooterId: "14478",
    city: "Nafplion",
    dateEntered: "2026-03-02",
    issueDescription: "Tire Replacement",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-03-05",
    notes: "Ripped tire Major, just came from Nafplion"
  },
  {
    scooterId: "54631",
    city: "Corinth",
    dateEntered: "2026-01-08",
    issueDescription: "Power Cutoff during riding",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-03-04",
    notes: "Now it works, has new motor in"
  },
  {
    scooterId: "52076",
    city: "Corinth",
    dateEntered: "2025-04-23",
    issueDescription: "IoT",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-03-02",
    notes: "Fixed With IoT"
  },
  {
    scooterId: "71527",
    city: "Corinth",
    dateEntered: "2026-02-08",
    issueDescription: "IoT",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-03-02",
    notes: "Fixed With IoT"
  },
  {
    scooterId: "85657",
    city: "Corinth",
    dateEntered: "2026-03-02",
    issueDescription: "Tire Replacement",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-03-02",
    notes: "Standard Procedure"
  },
  {
    scooterId: "68257",
    city: "Corinth",
    dateEntered: "2025-09-29",
    issueDescription: "IoT",
    category: "F",
    status: "Completed",
    primaryTag: "",
    secondaryTag: "",
    dateCompleted: "2026-02-25",
    notes: "Categorized as Q but It was actually B or C, didn't take that long but it had complex electronics work including using both diagnostics and a new process unaware to us which was SIM card swapping"
  },
  {
    scooterId: "88200",
    city: "Nafplion",
    dateEntered: "2026-02-14",
    issueDescription: "Neck Nut doesn't lock in",
    category: "C",
    status: "Investigation",
    primaryTag: "Unknown Process, Front Fork, Inspection",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "First nut doesn't lock in the fork, most likely guides are fucked, Requires 90 mins buffer"
  },
  {
    scooterId: "45704",
    city: "Nafplion",
    dateEntered: "2025-12-29",
    issueDescription: "Under water, needs inspection, need Iot",
    category: "C",
    status: "Investigation",
    primaryTag: "IoT, Inspection",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "Inspection needed, it's completely covered in salt, might need to decomission"
  },
  {
    scooterId: "61543",
    city: "Nafplion",
    dateEntered: "2026-02-14",
    issueDescription: "New Front Fork, battery doesn't unlock, New Bearing cap required",
    category: "C",
    status: "Investigation",
    primaryTag: "Front Fork, Unknown Process, Bearing Cap",
    secondaryTag: "Routine Maintenance",
    dateCompleted: null,
    notes: "Requires instalment of bearing that's why it's blocked"
  },
  {
    scooterId: "72330",
    city: "Corinth",
    dateEntered: "2026-03-12",
    issueDescription: "No connection",
    category: "B",
    status: "Investigation",
    primaryTag: "Inspection",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Completely Lost connecton, needs diagnostics check"
  },
  {
    scooterId: "27060",
    city: "Corinth",
    dateEntered: "2025-11-15",
    issueDescription: "Rear Brake Line Cover is fucked, needs a new one",
    category: "B",
    status: "Investigation",
    primaryTag: "Brake Lines, Inspection",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Need to know the SOP to replace this"
  },
  {
    scooterId: "83846",
    city: "Corinth",
    dateEntered: "2026-01-10",
    issueDescription: "Unresponsive, Headlight off look notes",
    category: "B",
    status: "Investigation",
    primaryTag: "Inspection",
    secondaryTag: "",
    dateCompleted: null,
    notes: "Needs close inspection, headlight was dim and then it stopped working,"
  },
];

export const SEED_PARTS = [
  {
    sku: "2010500214",
    partName: "Controllers",
    unitCost: 29.91,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2010800084",
    partName: "finger knob",
    unitCost: 3.49,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2010900037",
    partName: "Hall brake right",
    unitCost: 6.98,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2010900050",
    partName: "Bell brake handle (left)",
    unitCost: 8.14,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011000076",
    partName: "headlight",
    unitCost: 7.56,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011000086",
    partName: "Rear turn signal left",
    unitCost: 2.91,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011000097",
    partName: "Rear turn signal right",
    unitCost: 2.91,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300103",
    partName: "Wireless charging mobile phone holder",
    unitCost: 27.92,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300108",
    partName: "Meter adapting cable",
    unitCost: 2.33,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300117",
    partName: "Adapter cable",
    unitCost: 1.74,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300127",
    partName: "Adapter cable",
    unitCost: 4.65,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300128",
    partName: "Meter adapting cable",
    unitCost: 4.07,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011300150",
    partName: "Adapter cable",
    unitCost: 9.88,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011400060",
    partName: "Steering switch",
    unitCost: 4.42,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011600002",
    partName: "Magnetic ring",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011600005",
    partName: "Magnetic ring",
    unitCost: 0.24,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011800024",
    partName: "Hall sensor board",
    unitCost: 4.07,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2011800043",
    partName: "Lock box components",
    unitCost: 16.86,
    leadTime: 40,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020100038",
    partName: "Frame left rear plug cover",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020100039",
    partName: "Frame right rear plug cover",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020100040",
    partName: "Frame cover",
    unitCost: 0.24,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020100046",
    partName: "protective cover",
    unitCost: 0.11,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020200040",
    partName: "protective cover",
    unitCost: 0.11,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020600003",
    partName: "Instrument screen",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020700034",
    partName: "Fixed seat",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020700043",
    partName: "Fixed seat",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020700100",
    partName: "Fixed seat",
    unitCost: 5.24,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020800002",
    partName: "waterproof pad",
    unitCost: 0.11,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020800007",
    partName: "waterproof pad",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020900037",
    partName: "rear fender",
    unitCost: 3.49,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020900039",
    partName: "front fender",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2020900066",
    partName: "rear of front fender",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021000064",
    partName: "Handlebar upper cover",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021000065",
    partName: "Handlebar under cover",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021000072",
    partName: "Front fork left cover",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021000073",
    partName: "Front fork right cover",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021000080",
    partName: "ES400B frame front cover",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021300006",
    partName: "Left rear turn signal bracket",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021300007",
    partName: "Right rear turn signal bracket",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021300060",
    partName: "license plate bracket",
    unitCost: 0.58,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021500154",
    partName: "pedal pad",
    unitCost: 5.24,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021700008",
    partName: "reflector",
    unitCost: 0.7,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2021700009",
    partName: "Fixed strip",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2022100022",
    partName: "Gasket",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2022100025",
    partName: "battery protection pad",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2030500135",
    partName: "Tail light fixing piece",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2030700020",
    partName: "handlebar head",
    unitCost: 8.72,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2030800002",
    partName: "Handlebar lock cover",
    unitCost: 1.16,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031000017",
    partName: "front pole clamp",
    unitCost: 4.07,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031400014",
    partName: "Handlebar head wiring harness bracket",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031400026",
    partName: "Left tail light bracket",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031400027",
    partName: "Right tail light bracket",
    unitCost: 1.74,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031600021",
    partName: "kickstand",
    unitCost: 11.63,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031700024",
    partName: "Front fork retaining sleeve",
    unitCost: 5.24,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031700054",
    partName: "Bead bowl set fixing set",
    unitCost: 0.58,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2031800100",
    partName: "front fork set",
    unitCost: 20.93,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2036300005",
    partName: "Mechanical lock components",
    unitCost: 10.69,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100107",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100213",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100241",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100272",
    partName: "Countersunk head hexagon socket screws",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100276",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100304",
    partName: "Countersunk head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100305",
    partName: "Pan head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100310",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100326",
    partName: "Pan head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100328",
    partName: "Countersunk head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100330",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100343",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100346",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100347",
    partName: "Countersunk head plum blossom self-tapping screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100350",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100369",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100370",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100380",
    partName: "Semi-round head torx self-tapping screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100395",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100396",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.24,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100397",
    partName: "Half round head hexagon socket screws",
    unitCost: 0.24,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100398",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100407",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100410",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100413",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100418",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100420",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100425",
    partName: "Countersunk head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100427",
    partName: "Cylindrical head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100431",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100446",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100503",
    partName: "Pan head torx screws with column",
    unitCost: 0.24,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100517",
    partName: "Hexagon socket screws with cylindrical head",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100519",
    partName: "Half round head cross self-tapping screws",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100567",
    partName: "Pan head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040100851",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040200027",
    partName: "Ordinary nut",
    unitCost: 0.58,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040200028",
    partName: "cap nut",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040200035",
    partName: "flange nut",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040300038",
    partName: "Bearing",
    unitCost: 2.09,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040500041",
    partName: "Gasket",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040500048",
    partName: "Gasket",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040500050",
    partName: "Gasket",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040800002",
    partName: "rivet",
    unitCost: 0.11,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040800006",
    partName: "rivet",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040900041",
    partName: "Brake cable core",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040900049",
    partName: "Brake line skin",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040900051",
    partName: "Brake line skin",
    unitCost: 0.58,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040900058",
    partName: "Brake cable core",
    unitCost: 1.16,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2040900060",
    partName: "Brake line skin",
    unitCost: 1.16,
    leadTime: 20,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2041000173",
    partName: "Spacer",
    unitCost: 0.24,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2041000174",
    partName: "Spacer",
    unitCost: 0.24,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2042600002",
    partName: "Iron bowl seat",
    unitCost: 1.13,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2042800003",
    partName: "lower stopper",
    unitCost: 0.71,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2050100009",
    partName: "Foam",
    unitCost: 0.11,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "4060000060",
    partName: "ES400B/ES400C rear fork set (plastic spray)",
    unitCost: 6.4,
    leadTime: 0,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "4100000016",
    partName: "ES400 fender bracket welding group (plastic spray)",
    unitCost: 5.24,
    leadTime: 0,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "Shared"
  },
  {
    sku: "2010100184.0",
    partName: "Lithium-ion battery pack (with lithium-ion battery intelligent protection board BMS-13 series to 15 series software V1.0)",
    unitCost: 322.16,
    leadTime: 40,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2010200058",
    partName: "motor",
    unitCost: 41.87,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2010400033",
    partName: "Charging port",
    unitCost: 4.07,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2010600027",
    partName: "Meter",
    unitCost: 38.38,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2010700438",
    partName: "central control system",
    unitCost: 110.49,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011000110",
    partName: "taillight",
    unitCost: 6.98,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011000155",
    partName: "Front turn signal left",
    unitCost: 4.07,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011000156",
    partName: "Front turn signal right",
    unitCost: 4.07,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011200052",
    partName: "electronic lock",
    unitCost: 12.21,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011300132",
    partName: "Serial debugging cable",
    unitCost: 8.72,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2011300141",
    partName: "Serial port adapter cable",
    unitCost: 1.16,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2020500059",
    partName: "Grip",
    unitCost: 1.16,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2020700033",
    partName: "Fixed seat",
    unitCost: 2.91,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2030900059",
    partName: "handlebar pipe",
    unitCost: 2.91,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2031400019",
    partName: "Wireless charging bracket",
    unitCost: 4.07,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2031900106",
    partName: "front wheel set",
    unitCost: 23.88,
    leadTime: 35,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2032500058",
    partName: "Hub brake assembly",
    unitCost: 3.11,
    leadTime: 30,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2040100511",
    partName: "Countersunk head torx screws with column",
    unitCost: 0.11,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "2041100098",
    partName: "pin",
    unitCost: 1.33,
    leadTime: 25,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "3040100652",
    partName: "fender stickers",
    unitCost: 0.11,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "3040200102",
    partName: "QR code",
    unitCost: 0.35,
    leadTime: 15,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "4020000335",
    partName: "ES400 front straight bar (plastic spray)",
    unitCost: 13.38,
    leadTime: 0,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "4040000165",
    partName: "ES400B pedal cover (plastic spray)",
    unitCost: 5.24,
    leadTime: 0,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  },
  {
    sku: "4040001297",
    partName: "ES400B frame (plastic spray + labeling)",
    unitCost: 63.39,
    leadTime: 0,
    stockOnHand: 0,
    reorderPoint: 0,
    unitsOnOrder: 0,
    orderDate: null,
    eta: null,
    supplier: "",
    status: "",
    notes: "",
    model: "ES400B 2022"
  }
,
  {
    sku: "2010100185",
    partName: "Lithium-ion battery pack (with lithium-ion battery intelligent protection board BMS-13 series to 15 series software V1.0)",
    unitCost: 301.23, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2010200117",
    partName: "motor",
    unitCost: 52.34, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2010400006",
    partName: "Charging port",
    unitCost: 2.33, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2010600066",
    partName: "Meter",
    unitCost: 20.93, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2010700097",
    partName: "central control system",
    unitCost: 104.67, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2011000173",
    partName: "Front turn signal left",
    unitCost: 2.33, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2011000174",
    partName: "Front turn signal right",
    unitCost: 2.33, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2011000188",
    partName: "taillight",
    unitCost: 4.58, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2011200067",
    partName: "electronic lock",
    unitCost: 10.90, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2020100144",
    partName: "Handlebar tube left plug cover",
    unitCost: 0.58, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2020100145",
    partName: "Handlebar tube right plug cover",
    unitCost: 0.58, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2020500091",
    partName: "Grip",
    unitCost: 1.39, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2020700092",
    partName: "Fixed seat",
    unitCost: 3.49, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2030900090",
    partName: "handlebar pipe",
    unitCost: 4.65, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2031900070",
    partName: "front wheel set",
    unitCost: 20.80, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2032500003",
    partName: "Hub brake assembly",
    unitCost: 3.49, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "2040100447",
    partName: "Semi-round head torx screws with column",
    unitCost: 0.11, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "3040200083",
    partName: "QR code",
    unitCost: 0.35, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "4020000233",
    partName: "Phone holder with wireless charging",
    unitCost: 5.24, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "4040000236",
    partName: "ES400B pedal cover (plastic spray)",
    unitCost: 5.24, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "4040000950",
    partName: "ES400B frame (spray molded)",
    unitCost: 63.97, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  },
  {
    sku: "4190001828",
    partName: "ES400A front straight rod (plastic spraying + labeling)",
    unitCost: 16.28, leadTime: 0, stockOnHand: 0, reorderPoint: 0, unitsOnOrder: 0,
    orderDate: null, eta: null, supplier: "", status: "", notes: "", model: "ES400B 2023"
  }
];

export const SEED_CONFIG = {
  revenueRatePerDay: 3.67,
  maxActiveTickets: 3,
  seasonalityIndex: {
    jan: 2.39, feb: 2.68, mar: 3.58, apr: 3.54,
    may: 3.57, jun: 4.83, jul: 5.95, aug: 5.76,
    sep: 3.32, oct: 2.70, nov: 2.34, dec: 3.35,
  },
};