import { v4 as uuidv4 } from 'uuid';

/** Realistic sample data for a Greek micromobility operator with ~20 scooters */
export const SAMPLE_CONFIG = {
  fleetSize: 20,
  companyName: 'Omni',
  currency: 'EUR',
  targetCostPerScooter: 120,
};

export const SAMPLE_COSTS = [
  // ── Fixed Costs ──
  {
    id: uuidv4(),
    name: 'Business Insurance',
    category: 'fixed',
    amount: 350,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Comprehensive fleet insurance policy',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Office / Storage Rent',
    category: 'fixed',
    amount: 600,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Warehouse and operations office',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Staff Salary (1 FTE)',
    category: 'fixed',
    amount: 1200,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Operations & maintenance technician',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Platform / Software Subscription',
    category: 'fixed',
    amount: 280,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Fleet management IoT platform',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ── Variable Costs ──
  {
    id: uuidv4(),
    name: 'Battery Charging (Electricity)',
    category: 'variable',
    amount: 240,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Charging costs for full fleet, estimated',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Maintenance & Repairs',
    category: 'variable',
    amount: 400,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Parts, tyres, brake pads',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Payment Processing Fees',
    category: 'variable',
    amount: 90,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: '~1.5% of gross revenue',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Fuel / Van Transport',
    category: 'variable',
    amount: 150,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Rebalancing and retrieval trips',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── One-Off Costs ──
  {
    id: uuidv4(),
    name: 'Business Registration & Permits',
    category: 'one-off',
    amount: 1800,
    frequency: 'one-time',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Municipality operating permit + Greek business registration',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Branding & Website',
    category: 'one-off',
    amount: 2500,
    frequency: 'one-time',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'App design, website, brand identity',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Investments ──
  {
    id: uuidv4(),
    name: 'Scooter Fleet Purchase (20 units)',
    category: 'investment',
    amount: 1200,
    frequency: 'monthly',
    startDate: '2026-01-01',
    endDate: '2028-12-31',
    notes: 'Financing installment, 36-month loan',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Charging Infrastructure',
    category: 'investment',
    amount: 4500,
    frequency: 'one-time',
    startDate: '2026-01-01',
    endDate: null,
    notes: 'Charging racks and electrical installation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
