/**
 * Seed data — 7 pre-loaded projects from the spec.
 * Called once from Settings page if Firestore projects collection is empty.
 */

import { collection, getDocs, query, where, serverTimestamp } from 'firebase/firestore';
import { db } from '../lib/firebase.js';
import { orgWrite } from '../hooks/orgWrite.js';

const SEED_PROJECTS = [
  {
    name: 'Omni Nafplio Pilot',
    tagline: 'Full-season scooter operations in Nafplio',
    owner: 'Kostas',
    status: 'onTrack',
    projectType: 'Operations',
    linkedCity: 'Nafplion',
    tags: ['omni', 'nafplio'],
    startDate: '2026-01-01',
    targetDate: '2026-10-31',
    phases: [
      {
        id: 'phase-nafplio-1',
        number: 1,
        name: 'Fleet Deployment',
        doneCriteria: ['76 scooters operational', 'Hub location confirmed'],
        status: 'done',
        targetDate: '2026-03-01',
        actualDate: '2026-03-10',
        scopeCap: '',
        parallel: false,
      },
      {
        id: 'phase-nafplio-2',
        number: 2,
        name: 'Season Launch',
        doneCriteria: ['App live in Nafplio zone', 'First 100 rides logged'],
        status: 'inProgress',
        targetDate: '2026-04-30',
        actualDate: null,
        scopeCap: 'Does not include loyalty program — Phase 3',
        parallel: false,
      },
      {
        id: 'phase-nafplio-3',
        number: 3,
        name: 'Full Season Operations',
        doneCriteria: ['Revenue target hit', 'Maintenance cadence stable'],
        status: 'notStarted',
        targetDate: '2026-10-31',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Define phases and first next action for Nafplion season',
      dueDate: '2026-04-21',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'Omni Corinth',
    tagline: 'Scooter operations in Corinth',
    owner: 'Panos',
    status: 'onTrack',
    projectType: 'Operations',
    linkedCity: 'Corinth',
    tags: ['omni', 'corinth'],
    startDate: '2026-01-01',
    targetDate: '2026-10-31',
    phases: [
      {
        id: 'phase-corinth-1',
        number: 1,
        name: 'Fleet Deployment',
        doneCriteria: ['40 scooters operational', 'Hub confirmed'],
        status: 'inProgress',
        targetDate: '2026-04-30',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
      {
        id: 'phase-corinth-2',
        number: 2,
        name: 'Season Launch',
        doneCriteria: ['App live', 'Revenue generating'],
        status: 'notStarted',
        targetDate: '2026-06-01',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Confirm Corinth hub location with landlord',
      dueDate: '2026-04-18',
      owner: 'Panos',
      updatedAt: new Date().toISOString(),
    },
    blockers: [],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'OTORide Switch',
    tagline: 'Migrate fleet management to OTORide platform',
    owner: 'Kostas',
    status: 'blocked',
    projectType: 'Product',
    linkedCity: null,
    tags: ['otoride', 'platform'],
    startDate: '2026-03-01',
    targetDate: '2026-06-30',
    phases: [
      {
        id: 'phase-otoride-1',
        number: 1,
        name: 'AADE Integration',
        doneCriteria: ['Tax integration live', 'Test rides passing'],
        status: 'inProgress',
        targetDate: '2026-05-15',
        actualDate: null,
        scopeCap: 'Does NOT include driver payouts or loyalty program — those are Phase 3',
        parallel: false,
      },
      {
        id: 'phase-otoride-2',
        number: 2,
        name: 'Full Cutover',
        doneCriteria: ['All cities on OTORide', 'Old system decommissioned'],
        status: 'notStarted',
        targetDate: '2026-06-30',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Contact Giorgos at OTORide re: AADE integration timeline',
      dueDate: '2026-04-18',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [
      {
        id: 'blocker-otoride-1',
        text: 'AADE tax integration — waiting on OTORide team',
        type: 'external',
        resolved: false,
        escalation: 'Contact Giorgos by Apr 18',
        addedAt: '2026-04-02',
        resolvedAt: null,
      },
    ],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'POW Tracker',
    tagline: 'Internal tool for weekly progress tracking',
    owner: 'Kostas',
    status: 'onTrack',
    projectType: 'Product',
    linkedCity: null,
    tags: ['internal', 'tool'],
    startDate: '2026-04-01',
    targetDate: '2026-05-31',
    phases: [
      {
        id: 'phase-pow-1',
        number: 1,
        name: 'Build & Launch',
        doneCriteria: ['Weekly review dashboard live', 'POW logging working'],
        status: 'inProgress',
        targetDate: '2026-05-31',
        actualDate: null,
        scopeCap: 'Not a full task manager — just weekly review + POW logs',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Complete Projects module build and test with real data',
      dueDate: '2026-04-21',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'Franchise System',
    tagline: 'Develop a replicable franchise model for Omni',
    owner: 'Kostas',
    status: 'onTrack',
    projectType: 'Growth',
    linkedCity: null,
    tags: ['franchise', 'growth'],
    startDate: '2026-04-01',
    targetDate: '2026-12-31',
    phases: [
      {
        id: 'phase-franchise-1',
        number: 1,
        name: 'Model Design',
        doneCriteria: ['Franchise terms defined', 'Pilot city identified'],
        status: 'notStarted',
        targetDate: '2026-07-31',
        actualDate: null,
        scopeCap: 'Planning phase only — no legal work until model is agreed',
        parallel: false,
      },
      {
        id: 'phase-franchise-2',
        number: 2,
        name: 'Pilot Launch',
        doneCriteria: ['First franchisee signed', 'Operations running'],
        status: 'notStarted',
        targetDate: '2026-12-31',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Draft initial franchise terms document',
      dueDate: '2026-05-01',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'TEPIX III Loan',
    tagline: 'Secure TEPIX III government loan for fleet expansion',
    owner: 'Kostas',
    status: 'needsAttention',
    projectType: 'Finance',
    linkedCity: null,
    tags: ['finance', 'tepix', 'loan'],
    startDate: '2026-03-01',
    targetDate: '2026-06-30',
    phases: [
      {
        id: 'phase-tepix-1',
        number: 1,
        name: 'Application Submission',
        doneCriteria: ['All docs gathered', 'Application submitted to bank'],
        status: 'inProgress',
        targetDate: '2026-05-01',
        actualDate: null,
        scopeCap: 'Submission only — approval timeline is external',
        parallel: false,
      },
      {
        id: 'phase-tepix-2',
        number: 2,
        name: 'Approval & Drawdown',
        doneCriteria: ['Loan approved', 'Funds in account'],
        status: 'notStarted',
        targetDate: '2026-06-30',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Call Anastasia Togia re: TEPIX III docs by Friday',
      dueDate: '2026-04-18',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: 50000,
    budgetNotes: 'Loan amount TBC — estimated €50k based on fleet expansion plan',
    linkedProjectIds: [],
    archived: false,
  },
  {
    name: 'Nafplion Employee Hire',
    tagline: 'Hire local employee for Nafplion operations',
    owner: 'Kostas',
    status: 'needsAttention',
    projectType: 'Operations',
    linkedCity: 'Nafplion',
    tags: ['hr', 'nafplion'],
    startDate: '2026-04-01',
    targetDate: '2026-05-15',
    phases: [
      {
        id: 'phase-hire-1',
        number: 1,
        name: 'Recruitment',
        doneCriteria: ['Job post published', 'Candidates interviewed', 'Offer sent'],
        status: 'notStarted',
        targetDate: '2026-05-01',
        actualDate: null,
        scopeCap: 'One hire only — part-time to start',
        parallel: false,
      },
      {
        id: 'phase-hire-2',
        number: 2,
        name: 'Onboarding',
        doneCriteria: ['Contract signed', 'Employee trained on scooter ops'],
        status: 'notStarted',
        targetDate: '2026-05-15',
        actualDate: null,
        scopeCap: '',
        parallel: false,
      },
    ],
    nextAction: {
      text: 'Identify interview candidates for Nafplion role',
      dueDate: '2026-04-21',
      owner: 'Kostas',
      updatedAt: new Date().toISOString(),
    },
    blockers: [
      {
        id: 'blocker-hire-1',
        text: 'Interview candidates not yet identified',
        type: 'internal',
        resolved: false,
        escalation: '',
        addedAt: '2026-04-10',
        resolvedAt: null,
      },
    ],
    updates: [],
    decisions: [],
    powEntries: [],
    plannedBudget: null,
    budgetNotes: '',
    linkedProjectIds: [],
    archived: false,
  },
];

/**
 * Seeds the 7 launch projects into Firestore if this org has no projects yet.
 * Requires an orgId — uses org-scoped write so every seed doc carries orgId.
 * Returns true if seeded, false if org already had projects.
 */
export async function seedProjectsIfEmpty(orgId) {
  if (!orgId) throw new Error('seedProjectsIfEmpty: orgId is required');
  const snap = await getDocs(query(collection(db, 'projects'), where('orgId', '==', orgId)));
  if (!snap.empty) return false;

  for (const project of SEED_PROJECTS) {
    await orgWrite('projects', {
      ...project,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    }, { rethrow: true });
  }
  return true;
}
