import { createContext, useContext, useState, useCallback, useEffect, useMemo } from 'react';
import { isPowDay } from '../utils/powHelpers.js';

const NotificationContext = createContext(null);

/**
 * In-app notification system.
 * Notifications are generated by the Projects module and surfaced as:
 *  - badgeCount on the sidebar Projects nav item
 *  - a notifications array for a bell/banner in the top bar
 *
 * Notifications are stored in state only (session-scoped).
 * The Projects module pushes notifications via pushNotification().
 * Dismissed notifications stay in history but are marked dismissed.
 */
export function NotificationProvider({ children }) {
  const [notifications, setNotifications] = useState([]);

  // Seed a POW-day notification on Mondays
  useEffect(() => {
    if (isPowDay()) {
      setNotifications((prev) => {
        if (prev.some((n) => n.id === '__pow_day__')) return prev;
        return [
          {
            id: '__pow_day__',
            type: 'pow',
            message: 'Today is POW day — log your Progress of Week entries.',
            persistent: true,
            dismissed: false,
            createdAt: new Date().toISOString(),
          },
          ...prev,
        ];
      });
    }
  }, []);

  const pushNotification = useCallback((notification) => {
    setNotifications((prev) => {
      // Avoid exact duplicates by id
      if (notification.id && prev.some((n) => n.id === notification.id)) return prev;
      return [
        {
          dismissed: false,
          createdAt: new Date().toISOString(),
          ...notification,
        },
        ...prev,
      ];
    });
  }, []);

  const dismissNotification = useCallback((id) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, dismissed: true } : n)),
    );
  }, []);

  const dismissAll = useCallback(() => {
    setNotifications((prev) => prev.map((n) => ({ ...n, dismissed: true })));
  }, []);

  const activeNotifications = useMemo(
    () => notifications.filter((n) => !n.dismissed),
    [notifications],
  );
  const badgeCount = useMemo(() => activeNotifications.length, [activeNotifications]);

  return (
    <NotificationContext.Provider
      value={{
        notifications,
        activeNotifications,
        badgeCount,
        unreadCount: badgeCount, /* Omni alias */
        pushNotification,
        dismissNotification,
        dismissAll,
      }}
    >
      {children}
    </NotificationContext.Provider>
  );
}

export function useNotifications() {
  const ctx = useContext(NotificationContext);
  if (!ctx) throw new Error('useNotifications must be inside <NotificationProvider>');
  return ctx;
}
